version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./ys_python_challenge:/ys_python_challenge
    command: >
      sh -c "python manage.py migrate --settings=ys_python_challenge.settings.local &&
             python manage.py runserver 0.0.0.0:8000 --settings=ys_python_challenge.settings.local"
